services:
    nil_portugues.api.mapping.mapper:
          class: NilPortugues\Api\Mapping\Mapper
          arguments: []

    nil_portugues.api.json_api.json_api_transformer:
         class: NilPortugues\Api\JsonApi\JsonApiTransformer
         arguments:
            - "@nil_portugues.api.mapping.mapper"

    nil_portugues.serializer.json_api_serializer:
         class: NilPortugues\Symfony\JsonApiBundle\Serializer\JsonApiSerializer
         arguments:
            - "@nil_portugues.api.json_api.json_api_transformer"
            - "@router"
